### PR TITLE
fixed config mutation in state

### LINKED ISSUE #144: context.run mutates adds default values to input config
Scenario should mutate the input state as little as necessary.

It is desirable that, if you passed no config, the output state still has no config.

```
traefik_state = State(config={})
state_out = traefik_ctx.run('update-status', traefik_state)

assert state_out.config == {}
```

However scenario needs to present **some data** to the config-get hook and so it populates the config before running the charm. 
However, it forgets to clean it up by removing any keys that were added by scenario itself in the process.

### PR DESCRIPTION
**Pull request by PietroPasotti**
Fixes #144 

`config_get` had a subtle bug causing the state_in.config to be mutated when called.
Fixed by copying the input config.

### CODE REVIEW

**Comment by PietroPasotti** [comment]
@tonyandrewmeyer do we cherry pick this in the 7.0 branch, or do you want to do a larger final rebase before releasing?

**Comment by tonyandrewmeyer** [comment]
> @tonyandrewmeyer do we cherry pick this in the 7.0 branch, or do you want to do a larger final rebase before releasing?

Yeah, good question. I have ignored it so far, but really ought to get the main changes into 7. Do you have any preference?

**Comment by PietroPasotti** [comment]
not really, I guess it's easier to do a rebase to avoid missing anything?

**Comment by tonyandrewmeyer** [comment]
> not really, I guess it's easier to do a rebase to avoid missing anything?

Probably yes. I wish I had paid more attention earlier and realised that I was not squashing when I merged into 7.0 :disappointed:.

I'll work on cleaning this up.

**Pull request merged**
